[package]
name = "akatsuki-pp-py"
version = "0.9.3"
description = "osu! difficulty and pp calculation for all modes"
authors = ["Max Ohn <ohn.m@hotmail.de>", "tsunyoku <tsunyoku@gmail.com>"]
license = "MIT"
edition = "2021"

[lib]
name = "akatsuki_pp_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module", "macros"] }
akatsuki-pp = { git = "https://github.com/osuAkatsuki/akatsuki-pp-rs", rev = "e22fe936337f3306fde2afec065f943c05e344f3" }

[profile.release]
lto = "fat"
codegen-units = 1
strip = "debuginfo"
